/**
 * i18n-vertalingen voor Shift Happens (nl/en).
 * Wordt geladen vóór app.js; app.js gebruikt window.TRANSLATIONS.
 */
window.TRANSLATIONS = {
    nl: {
        settings: { colorMode: 'Kleurmodus', language: 'Taal', title: 'Instellingen', save: 'Opslaan', saved: 'Instellingen opgeslagen!', theme: 'Thema', touchscreenMode: 'Touchscreen-modus', touchscreenModeHint: 'Grotere scrollbalk en grotere tikgebieden voor gebruik op aanraakschermen (bijv. Raspberry Pi-kiosk).', venueOrder: 'Zaalvolgorde', venueOrderHint: 'Sleep de zalen om de volgorde aan te passen. Klik op het oog om een zaal te verbergen in de zaal-dropdown.', resetVenueOrder: 'Reset naar standaard', techOptions: 'Technische opties per zaal', techOptionsHint: 'Kies per zaal welke opties (balletvloer, vleugel, orkestbak) getoond worden.', yesplan: 'Yesplan', activeOrg: 'Actieve organisatie', activeOrgHint: 'Bepaal welke Yesplan-organisatie het dashboard gebruikt', org1: 'Organisatie 1', org2: 'Organisatie 2', orgN: 'Organisatie {n}', bothOrgs: 'Beide organisaties', name: 'Naam', baseURL: 'Base URL', apiKey: 'API Key', loadVenues: 'Laad Zalen', loadVenuesHint: 'Haalt zalen op voor zaalvolgorde en header', loadVenuesFullHint: 'Vul per organisatie Base URL en API Key in, klik op "Laad Zalen"', testConnection: 'Test Verbinding', about: 'Over deze app', showVenue: 'Zaal tonen', hideVenue: 'Zaal verbergen', balletvloer: 'Balletvloer', vleugel: 'Vleugel', orkestbak: 'Orkestbak' },
        status: { online: 'Online', offline: 'Offline', deels: 'Deels bereikbaar', warning: 'Waarschuwing', systemStatus: 'Systeemstatus', clickForStatus: 'Klik voor systeemstatus' },
        nav: { back: 'Terug', backTitle: 'Terug naar vorig scherm', home: 'Home', weekView: 'Weekoverzicht', techOverview: 'Technisch overzicht', techOverviewTitle: 'Print technisch overzicht voor deze dag (alle zalen)', prevDay: 'Vorige dag', nextDay: 'Volgende dag', refresh: 'Vernieuwen', searchEvent: 'Zoek evenement', searchEventTitle: 'Zoek op evenementnaam (* en ? als wildcard)' },
        search: { placeholder: 'Evenementnaam… (* = alles, ? = één teken)', noResults: 'Geen evenementen gevonden.', noResultsFor: 'Geen evenementen gevonden voor "{query}". Probeer een andere zoekterm.', minChars: 'Typ minstens 2 tekens om te zoeken.', wildcardHint: 'Gebruik * voor een reeks tekens en ? voor één teken, bv. *congres*' },
        date: { today: 'Vandaag', chooseDate: 'Kies eigen datum', selectDate: 'Selecteer datum:', manualDate: 'Of voer handmatig in (dd-mm-jjjj):', datePlaceholder: 'dd-mm-jjjj', confirm: 'Bevestigen', cancel: 'Annuleren' },
        venue: { allVenues: 'Alle zalen', venue: 'Zaal', unknownVenue: 'Onbekende zaal', venueCount: '{n} zalen', venueId: 'Zaal {id}' },
        filters: { title: 'Filters', hideCancelled: 'Verberg geannuleerde voorstellingen', technischPersoneel: 'Alleen evenementen met technisch personeel', technischeResources: 'Alleen evenementen met technische resources' },
        weekView: { title: 'Weekoverzicht', sortByVenue: 'Op zaal', sortByVenueTitle: 'Sorteren op zaal (instellingen volgorde)', sortByTime: 'Op tijd', sortByTimeTitle: 'Sorteren op tijd' },
        cards: { yesplan: 'Yesplan', personnel: 'Personeel', itix: 'Itix - Kaartverkoop', priva: 'Priva - Klimaat', tijdschema: 'Tijdschema' },
        personnel: { techniek: 'Techniek', horeca: 'Horeca', frontOffice: 'Front Office' },
        dataStats: { capaciteit: 'Capaciteit', verkocht: 'Verkocht', gereserveerd: 'Gereserveerd', beschikbaar: 'Beschikbaar', omzet: 'Omzet', gasten: 'Gasten', totaal: 'Totaal', transacties: 'Transacties', omzetEur: 'Omzet (€)', temp: 'Temperatuur', luchtvochtigheid: 'Luchtvochtigheid', luchtkwaliteit: 'Luchtkwaliteit', co2: 'CO₂' },
        tech: { materiaal: 'Technisch materiaal:', lijst: 'Technische lijst:', lijstBijlage: 'Technische lijst bijlage:' },
        resources: { ja: 'ja', nee: 'nee', nietBekend: 'niet ingevuld' },
        loading: 'Laden...',
        messages: { noEvents: 'Geen evenementen gevonden voor {venue} op {date}', noEventsDate: 'Geen evenementen gevonden op {date}', noEventsWeek: 'Geen evenementen in deze week voor {venue}.', selectDayVenueTijdschema: 'Selecteer 1 dag en 1 zaal om het tijdschema te zien.', noTijdschema: 'Geen tijdschema beschikbaar voor deze evenementen.', noPlanning: 'Geen planning beschikbaar voor deze dag', noVerkoop: 'Geen verkoopdata beschikbaar voor deze dag', noKlimaat: 'Geen klimaatdata beschikbaar', venueOrderReset: 'Zaalvolgorde gereset naar standaard', loadVenuesFirst: 'Laad eerst zalen in de Yesplan instellingen.', venuesLoaded: '{n} zalen geladen', configureBothOrgs: 'Configureer eerst beide organisaties voor "Beide"', fillBaseUrlApiKey: 'Vul eerst Base URL en API Key in voor organisatie {n}' },
        techPrint: { title: 'Technisch overzicht', subtitle: 'Alle zalen – {date}', noEvents: 'Geen evenementen op deze dag.', venue: 'Zaal', time: 'Tijd', remarks: 'Opmerkingen techniek', documents: 'Technische lijst documenten', filterTitle: 'Evenementen voor print', filterHint: 'Vink de evenementen aan die in het overzicht moeten komen.', selectAll: 'Alles selecteren', deselectAll: 'Alles deselecteren', pdfCredit: 'PDF-export op suggestie van Gerbrand.' },
        errors: { yesplanLoad: 'Kon Yesplan data niet laden', eventsLoad: 'Kon evenementen niet laden', weekLoad: 'Kon weekoverzicht niet laden', uurwerkLoad: 'Kon personeelsplanning niet laden', itixLoad: 'Kon Itix data niet laden', privaLoad: 'Kon Priva data niet laden', settingsSave: 'Kon instellingen niet opslaan', apiServerInvalid: 'Ongeldige API-server-URL. Gebruik bijvoorbeeld http://192.168.1.10:3847', apiServerWrongKind: 'Server-URL is voor de Shift Happens API (poort 3847), niet voor Yesplan of de Itix-zaalplattegrond. Vul Yesplan/Itix verderop in dit formulier in.' },
        test: { testing: 'Testen...', success: 'Succesvol', failed: 'Gefaald' }
    },
    en: {
        settings: { colorMode: 'Color mode', language: 'Language', title: 'Settings', save: 'Save', saved: 'Settings saved!', theme: 'Theme', touchscreenMode: 'Touchscreen mode', touchscreenModeHint: 'Larger scrollbar and tap targets for use on touchscreens (e.g. Raspberry Pi kiosk).', venueOrder: 'Venue order', venueOrderHint: 'Drag venues to change the order. Click the eye to hide a venue in the venue dropdown.', resetVenueOrder: 'Reset to default', techOptions: 'Technical options per venue', techOptionsHint: 'Choose per venue which options (dance floor, grand piano, orchestra pit) are shown.', yesplan: 'Yesplan', activeOrg: 'Active organisation', activeOrgHint: 'Determine which Yesplan organisation the dashboard uses', org1: 'Organisation 1', org2: 'Organisation 2', orgN: 'Organisation {n}', bothOrgs: 'Both organisations', name: 'Name', baseURL: 'Base URL', apiKey: 'API Key', loadVenues: 'Load Venues', loadVenuesHint: 'Fetches venues for order and header', loadVenuesFullHint: 'Enter Base URL and API Key per organisation, click "Load Venues"', testConnection: 'Test Connection', about: 'About this app', showVenue: 'Show venue', hideVenue: 'Hide venue', balletvloer: 'Dance floor', vleugel: 'Grand piano', orkestbak: 'Orchestra pit' },
        status: { online: 'Online', offline: 'Offline', deels: 'Partially available', warning: 'Warning', systemStatus: 'System status', clickForStatus: 'Click for system status' },
        nav: { back: 'Back', backTitle: 'Back to previous screen', home: 'Home', weekView: 'Week overview', techOverview: 'Technical overview', techOverviewTitle: 'Print technical overview for this day (all venues)', prevDay: 'Previous day', nextDay: 'Next day', refresh: 'Refresh', searchEvent: 'Search event', searchEventTitle: 'Search by event name (* and ? as wildcards)' },
        search: { placeholder: 'Event name… (* = any, ? = one character)', noResults: 'No events found.', noResultsFor: 'No events found for "{query}". Try a different search term.', minChars: 'Type at least 2 characters to search.', wildcardHint: 'Use * for any characters and ? for one character, e.g. *congress*' },
        date: { today: 'Today', chooseDate: 'Choose date', selectDate: 'Select date:', manualDate: 'Or enter manually (dd-mm-yyyy):', datePlaceholder: 'dd-mm-yyyy', confirm: 'Confirm', cancel: 'Cancel' },
        venue: { allVenues: 'All venues', venue: 'Venue', unknownVenue: 'Unknown venue', venueCount: '{n} venues', venueId: 'Venue {id}' },
        filters: { title: 'Filters', hideCancelled: 'Hide cancelled performances', technischPersoneel: 'Only events with technical staff', technischeResources: 'Only events with technical resources' },
        weekView: { title: 'Week overview', sortByVenue: 'By venue', sortByVenueTitle: 'Sort by venue (settings order)', sortByTime: 'By time', sortByTimeTitle: 'Sort by time' },
        cards: { yesplan: 'Yesplan', personnel: 'Personnel', itix: 'Itix - Box office', priva: 'Priva - Climate', tijdschema: 'Schedule' },
        personnel: { techniek: 'Technical', horeca: 'Catering', frontOffice: 'Front Office' },
        dataStats: { capaciteit: 'Capacity', verkocht: 'Sold', gereserveerd: 'Reserved', beschikbaar: 'Available', omzet: 'Revenue', gasten: 'Guests', totaal: 'Total', transacties: 'Transactions', omzetEur: 'Revenue (€)', temp: 'Temperature', luchtvochtigheid: 'Humidity', luchtkwaliteit: 'Air quality', co2: 'CO₂' },
        tech: { materiaal: 'Technical equipment:', lijst: 'Technical list:', lijstBijlage: 'Technical list attachment:' },
        resources: { ja: 'yes', nee: 'no', nietBekend: 'not filled in' },
        loading: 'Loading...',
        messages: { noEvents: 'No events found for {venue} on {date}', noEventsDate: 'No events found on {date}', noEventsWeek: 'No events this week for {venue}.', selectDayVenueTijdschema: 'Select 1 day and 1 venue to see the schedule.', noTijdschema: 'No schedule available for these events.', noPlanning: 'No schedule available for this day', noVerkoop: 'No sales data available for this day', noKlimaat: 'No climate data available', venueOrderReset: 'Venue order reset to default', loadVenuesFirst: 'Load venues first in Yesplan settings.', venuesLoaded: '{n} venues loaded', configureBothOrgs: 'Configure both organisations first for "Both"', fillBaseUrlApiKey: 'Enter Base URL and API Key first for organisation {n}' },
        techPrint: { title: 'Technical overview', subtitle: 'All venues – {date}', noEvents: 'No events on this day.', venue: 'Venue', time: 'Time', remarks: 'Technical remarks', documents: 'Technical list documents', filterTitle: 'Events for print', filterHint: 'Select which events to include in the overview.', selectAll: 'Select all', deselectAll: 'Deselect all', pdfCredit: 'PDF export suggested by Gerbrand.' },
        errors: { yesplanLoad: 'Could not load Yesplan data', eventsLoad: 'Could not load events', weekLoad: 'Could not load week overview', uurwerkLoad: 'Could not load personnel planning', itixLoad: 'Could not load Itix data', privaLoad: 'Could not load Priva data', settingsSave: 'Could not save settings', apiServerInvalid: 'Invalid API server URL. Example: http://192.168.1.10:3847', apiServerWrongKind: 'This field is for the Shift Happens API server (port 3847), not Yesplan or the Itix seating URL. Use Yesplan/Itix sections below.' },
        test: { testing: 'Testing...', success: 'Success', failed: 'Failed' }
    }
};
